FROM borovlevas/odoo-base:19.0

# You can add additional Python packages required for your Odoo project here.
# COPY extra_addons/extra_requirements.txt /tmp/extra_requirements.txt
# RUN pip3 install --no-cache-dir -r /tmp/extra_requirements.txt